[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Humboldt-WI/bads/blob/master/exercises/1_ex_python.ipynb) 

# BADS Exercise 1 on Python programming
We covered a lot of concepts in the first [tutorial on Python programming](https://github.com/Humboldt-WI/bads/blob/master/tutorials/1_nb_python_intro.ipynb). Solving the exercises allows you to test your familiarity with these concepts.  

## Variables, assignments, and comparisons

1. Create two variables $a$ and $b$ and assign values of $3$ and $4.5$.

In [15]:
a , b = 3, 4.5

2. Query the type of variable $a$.

In [16]:
type(a)

int

3. Check whether variable $b$ is a text variable.

4. Calculate $a^2 + \frac{1}{b}$, $\sqrt{a*b}$, and $log_2(a)$.

In [17]:
a**2+1/b

9.222222222222221

In [18]:
import math
print(math.sqrt(a*b))
print(math.log(a))

3.6742346141747673
1.0986122886681098


## Matrix algebra
Create three additional variables as follows:

 $$ A = \left( \begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 10 \end{matrix} \right) \quad
  B = \left( \begin{matrix} 1 & 4 & 7 \\ 2 & 5 & 8 \\ 3 & 6 & 9 \end{matrix} \right)  \quad
  y = \left( \begin{matrix} 1 \\ 2 \\ 3 \end{matrix} \right) $$

Perform the following operations. Note that mathematical operators like `*` might not behave in the way you need it. Wasn't there a powerful library for all sorts of numerical computations including classic linear algebra?

Calculate  

  1. $a*A$

In [19]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,10]])
print( np.multiply(a,A))

[[ 3  6  9]
 [12 15 18]
 [21 24 30]]


  2. $A*B$

In [20]:
B = np.array([[1,4,7],[2,5,8],[3,6,9]])
print( np.multiply(A, B))

[[ 1  8 21]
 [ 8 25 48]
 [21 48 90]]


  3. The inverse of matrix $A$ and store the result in a variable $invA$. Any ideas how to get Python to invert a matrix? Hint: NumPy is your friend.  

In [21]:
invA = np.linalg.inv(A)
invA

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

  4. Multiply $A$ and $invA$ and verify that the result is the identity matrix (i.e. only 1s on the diagonal). You'll probably find that it isn't, because computers usually make very small rounding error when handling real numbers. The reason is interesting, but you'll have to look it up if you're interested.

In [22]:
print(A)
print(np.multiply(A, invA))
print(np.allclose(np.dot(invA, A), np.eye(3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[ -0.66666667  -2.66666667   3.        ]
 [ -2.66666667  18.33333333 -12.        ]
 [  7.         -16.          10.        ]]
True


  5. The transpose of matrix $B$

In [23]:
print(B.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


  6. Fill the first row of matrix $B$ with ones

In [24]:
B = np.array([[1,4,7],[2,5,8],[3,6,9]])
print(B)
B[0:2]=1
print(B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 1 1]
 [1 1 1]
 [3 6 9]]


  7. Calculate the ordinary least squares estimator $\beta$ (i.e. a standard regression) 
$$ \beta = (A^{\top}A)^{-1}A^{\top} y $$ Run a web search for "Python matrix transpose" to get help on how to transpose a matrix. 

In [34]:
y = np.array([1,2,3]).T
beta = np.multiply(np.multiply(np.linalg.inv(np.multiply(A.T, A)), A.T), y)
print(beta)

[[-0.17801998 -1.51135332  2.6893733 ]
 [-0.37783833  3.09718438 -2.61580381]
 [ 0.38419619 -1.30790191  1.0626703 ]]


## Indexing
1. Look at values of variables $A$, $B$, and $y$ from the last exercise

In [35]:
print(A, B, y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]] [[1 1 1]
 [1 1 1]
 [3 6 9]] [1 2 3]


2. Access the second element in the third row of $A$ and the first element in the second row of $B$, and compute their product

In [40]:
print(np.multiply(A[2][1],B[1][0]))

8


3. Multiply the first row of $A$ and the third column of $B$

In [55]:
print(A[:1])
print(B[:,[2]])
np.multiply(A[:1], B[:,[2]])

[[1 2 3]]
[[1]
 [1]
 [9]]


array([[ 1,  2,  3],
       [ 1,  2,  3],
       [ 9, 18, 27]])

4. Access the elements of y that are greater than 1 (without looking up their position manually)

In [58]:
for i in y:
    if i>1:
        print(i)

2
3


5. Access the elements of A in the second column, for which the values in the first column are greater or equal to 4)

In [59]:
for i in A[:,[1]]:
    if i>=4:
        print(i)

[5]
[8]


6. Access the 4th row of A. If this returns an error message, use Google to investigate the problem and find out what went wrong.

In [60]:
print(A[3])

IndexError: index 3 is out of bounds for axis 0 with size 3

## Custom functions
For many statistical applications it is practical to standardize variable values. One way to standardize is *centering and scaling*. In simple words, we make the variables comparable by reducing them to the same scale.

Start with implementing a custom function. Your function should take an argument **x**. To keep things simple, we expect x to always be a numeric vector (and not text or a matrix, for example). In the body of the function, calculate the mean and standard deviation of **x**. Store the results in variables  **mu** and **std**, respectively. Then for each element in the vector, substract the mean and divide by the standard deviation.
$$ x_{new} = \frac{x-\mu}{std}$$
Make sure your functions **returns** the standardized vector (i.e., $x_new$ in the equation) as result. You might want to import `NumPy` for calculating the mean and standard deviation.

In [68]:
def custom(x):
    mu = np.mean(x)
    std = np.std(x)
    return np.divide(x-mu, std)

You should always test your functions. Create a vector **a** with the elements (-100, -25, -10, 0, 10, 25, 100) and check if your function produces the correct result.     

In [69]:
a = np.array([-100, -25, -10, 0, 10, 25, 100]) 
print(a)
custom(a)

[-100  -25  -10    0   10   25  100]


array([-1.80648921, -0.4516223 , -0.18064892,  0.        ,  0.18064892,
        0.4516223 ,  1.80648921])

*Optional*: Create a vector **b** with elements ("1", "2", "3") and check the function. Let's include a simple check in the function and give feedback. Before doing any calculations, use `if()` and `type()` to check if the input is a numeric vector. There are many ways to code the condition *x is numeric* in Python. Run a quick web search and use a simple approach. If the input is not numeric, skip the computations and print a message "input not numeric".

## Data structures 
Say you want to keep track of the members of the four houses of the famous Hogwarts School of Witchcraft and Wizardry. What might be a suitable data structure. We create a dictionary named **hogwarts** and use the names of the houses as keys. Then, the values associated with those keys could be any type that supports storing a set of strings, i.e., to store the names of the members. Draw on your knowledge of Python dictionaries and list to implement such a data structure. Populate the dictionary with the following data, and feel free to add more characters if you wish. 

- Gryffindor: I'm sure you know many members of that house 
- Hufflepuff: notable members include Newt Scamander, Cedric Diggory and Nymphadora Tonks
- Ravenclaw: here we've got, e.g. Luna Lovegood, Gilderoy Lockhart and Filius Flitwick
- Slytherin: Draco Malfoy, Vincent Crabbe, Gregory Goyle, and of course the one that must not be named

In [70]:
hogwart= {Gryffindor: "I'm sure you know many members of that house"}

NameError: name 'Gryffindor' is not defined

Dictionaries are really useful. Still our above data structure is limited. We can only store the name of a witch or wizard. Wouldn't it be cool to be able to store more information, something like her/his favored charm, best friend, pet, etc. 

Think about how we could realize this functionality. Well, we could create yet another dictionary in which we use a witch's/wizard's name as key and as value some some other data structure in which we can store all the details we like. To our knowledge, the names of witches / wizards are unique in the Harry Potter universe, so that names could serve as (unique) keys; nerd alert. Still a dictionary of dictionaries sounds pretty complicated. In fact, the task we described above is a perfect use case of customer classes. They allow us to store any piece of information about a person at one place.

Create a custom class wizard that facilitates storing the following properties:
- First name
- Last name
- Pet
- Pet name
- Patronus shape


Also implement a method `tell_pet()`that prints an output of the following format:
*"Harry Potter's owl is called Hedwig."* 

Implement one more  method `expecto_patronum()`. Calling that method for Harry would produce the output (print):
*"A stag appears."*

In [76]:
class wizard():
    def __init__(self, first_name, last_name, pet, pet_name, patronus_shape):
        self.first_name, self.last_name, self.pet, self.pet_name, self.patronus_shape=first_name, last_name, pet, pet_name, patronus_shape
        
    def tell_pet(self):
        print(f'{self.first_name} {self.last_name}\'s {self.pet} is called {self.pet_name}.')
         
    def expecto_patronum(self):
        print(f'A {self.patronus_shape} appears.')

Update your dictionary with schools and their members. Instead of storing a list of names as values, your new dictionary should store a list of instances of the class wizard. Note that you need to create these instances first. So you need to create an instance of class wizard for Harry, another one for Ron, Malfoy, etc. In case your knowledge of the Potter universe is a bit shaky, just invent the data you need. Just in case, [here is a ittle refresher of the expecto patronum spell](https://www.insider.com/harry-potter-characters-patronus-2018-11).

In [78]:
harry = wizard('harry','potter', 'owl', 'hedwig', 'stag')
harry.tell_pet()
harry.expecto_patronum()

harry potter's owl is called hedwig.
A stag appears.


## Well done!!!